# Generated by Django 2.1.7 on 2019-03-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzer', '0002_auto_20190304_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='general_expenses',
            name='Email',
        ),
        migrations.AlterField(
            model_name='general_expenses',
            name='T_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
