# Generated by Django 2.1.7 on 2019-03-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzer', '0003_auto_20190304_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandatory_expenses',
            name='Email',
        ),
        migrations.AddField(
            model_name='mandatory_expenses',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mandatory_expenses',
            name='T_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
