# Generated by Django 2.1.7 on 2019-03-04 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzer', '0004_auto_20190304_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandatory_expenses',
            name='date',
        ),
    ]
