# Generated by Django 2.1.7 on 2019-03-04 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzer', '0005_remove_mandatory_expenses_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandatory_expenses',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
